# Generated by Django 5.2.5 on 2026-01-21 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolesow',
            name='end_client',
        ),
        migrations.AddField(
            model_name='rolesow',
            name='main_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolesows', to='employees.mainclient'),
        ),
    ]
