# Generated by Django 5.2.5 on 2026-01-21 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_task_created_on_task_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(help_text='Laptop, Headphones, Mouse, Keyboard, Monitor', max_length=50)),
                ('asset_color', models.CharField(blank=True, max_length=30, null=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('purchased_date', models.DateField(blank=True, null=True)),
                ('last_repaired_on', models.DateField(blank=True, null=True)),
                ('last_repair_details', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_on', models.DateField()),
                ('returned_on', models.DateField(blank=True, null=True)),
                ('is_with_employee', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='employees.employee')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='employees.assetinventory')),
            ],
        ),
    ]
