# Generated by Django 5.2.5 on 2026-01-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_assetinventory_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinventory',
            name='optional_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='purchased_at',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
