# Generated by Django 5.2.5 on 2026-02-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_employee_serial_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sow_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sow_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
